CREATE TEMPORARY TABLE ANALYTICS_SCRIPTS_TEST USING CarbonAnalytics OPTIONS ( tableName "ANALYTICS_SCRIPTS_TEST", schema "server_name string, ip STRING, tenant INTEGER, sequence LONG, summary STRING" );

SELECT ip FROM ANALYTICS_SCRIPTS_TEST;

SELECT server_name, count(*) FROM ANALYTICS_SCRIPTS_TEST GROUP BY server_name;

SELECT COUNT(*) FROM ANALYTICS_SCRIPTS_TEST WHERE summary LIKE '%Joe%';

SELECT substr(summary, 1, 5) FROM ANALYTICS_SCRIPTS_TEST;

SELECT LAST(ip) FROM ANALYTICS_SCRIPTS_TEST;

SELECT SQRT(CAST(sequence AS STRING)) FROM ANALYTICS_SCRIPTS_TEST;
