var datasource, datasourceType, columns,filter;

var REFRESH_INTERVAL = 5000;

//this needs to be loaded from an autogenerated
datasource = gadgetConfig.datasource;
filter = gadgetConfig.filter;

//first, fetch datasource schema
getColumns(datasource);

//load data immediately
fetchData(drawChart);

// then start periodic polling
setInterval(function() {
    fetchData(drawChart);
},REFRESH_INTERVAL);


function getColumns(table) {
    console.log("Fetching table schema for table: " + table);
    var url = "/designer/apis/analytics?action=getSchema&tableName=" + table;
    $.getJSON(url, function(data) {
        if (data) {
            columns = data;
        }

    });
};

function fetchData(callback) {
    var timeFrom = new Date("1970-01-01").getTime();
    var timeTo = new Date().getTime();
    var request = {
        action: "getData",
        tableName: datasource,
        filter:filter,
        timeFrom: timeFrom,
        timeTo: timeTo,
        start: 0,
        count: 10
    };
    $.ajax({
        url: "/designer/apis/analytics",
        method: "GET",
        data: request,
        contentType: "application/json",
        success: function(data) {
            if (callback != null) {
                callback(makeRows(data));
            }
        }
    });
};

function makeDataTable(data) {
    var dataTable = new igviz.DataTable();
    if (columns.length > 0) {
        columns.forEach(function(column, i) {
            var type = "N";
            if (column.type == "STRING" || column.type == "string") {
                type = "C";
            }
            dataTable.addColumn(column.name, type);
        });
    }
    if (data.length > 0) {
        dataTable.addRows(data);
    }
    return dataTable;
};

function makeRows(data) {
    var rows = [];
    for (var i = 0; i < data.length; i++) {
        var record = data[i];
        var keys = Object.getOwnPropertyNames(record.values);
        var row = columns.map(function(column, i) {
            return record.values[column.name];
        });
        rows.push(row);
    };
    return rows;
};

function drawChart(data) {
    var dataTable = makeDataTable(data);
    gadgetConfig.chartConfig.width = $("#placeholder").width();
    gadgetConfig.chartConfig.height = $("#placeholder").height() - 65;

    if(gadgetConfig.chartConfig.chartType==="table") {
        igviz.draw("#placeholder", gadgetConfig.chartConfig, dataTable);
    } else {
        var chart = igviz.setUp("#placeholder", gadgetConfig.chartConfig, dataTable);
        chart.setXAxis({
                "labelAngle": -35,
                "labelAlign": "right",
                "labelDy": 0,
                "labelDx": 0,
                "titleDy": 25
            })
            .setYAxis({
                "titleDy": -30
            })
            

        chart.plot(dataTable.data);
    }
};